import { RoleName } from '@prisma/client';

export const PERMISSION_DEFINITIONS = [
  ['auth:me', 'Read own profile'],
  ['users:read', 'Read users'],
  ['users:create', 'Create users'],
  ['users:write', 'Update users'],
  ['users:manage', 'Manage user status'],
  ['references:read', 'Read reference data'],
  ['references:create', 'Create reference data'],
  ['references:update', 'Update reference data'],
  ['references:delete', 'Delete reference data'],
  ['products:read', 'Read products'],
  ['products:create', 'Create products'],
  ['products:update', 'Update products'],
  ['products:delete', 'Delete products'],
  ['products:manage_prices', 'Manage product prices'],
  ['products:read_purchase_price', 'Read purchase prices and margins'],
  ['clients:read', 'Read clients'],
  ['clients:read_all', 'Read all clients'],
  ['clients:create', 'Create clients'],
  ['clients:update', 'Update clients'],
  ['clients:delete', 'Delete clients'],
  ['leads:read', 'Read leads'],
  ['leads:read_all', 'Read all leads'],
  ['leads:create', 'Create leads'],
  ['leads:update', 'Update leads'],
  ['leads:delete', 'Delete leads'],
  ['leads:qualify', 'Qualify leads'],
  ['leads:commercial_qualify', 'Confirm Stage-2 commercial qualification'],
  ['leads:assign', 'Assign leads'],
  ['tasks:read', 'Read tasks'],
  ['tasks:read_all', 'Read all tasks'],
  ['tasks:create', 'Create tasks'],
  ['tasks:update', 'Update tasks'],
  ['tasks:delete', 'Delete tasks'],
  ['deals:read', 'Read deals'],
  ['deals:read_all', 'Read all deals'],
  ['deals:create', 'Create deals'],
  ['deals:update', 'Update deals'],
  ['deals:delete', 'Delete deals'],
  ['deals:create_offer', 'Create deal offers'],
  ['deals:approve_offer', 'Approve deal offers'],
  ['deals:stage_exception', 'Approve deal stage exceptions'],
  ['deals:override_terminal', 'Override terminal deal stage'],
  ['orders:read', 'Read orders'],
  ['orders:create', 'Create orders'],
  ['orders:cancel', 'Cancel orders'],
  ['payments:create', 'Create payments'],
  ['payments:confirm', 'Confirm payments'],
  ['deliveries:create', 'Create deliveries'],
  ['inventory:read', 'Read inventory'],
  ['inventory:manage', 'Manage inventory'],
  ['warehouse_purchases:plan', 'Create and manage warehouse purchases'],
  [
    'warehouse_purchases:receive',
    'Record physical warehouse purchase receipts',
  ],
  ['files:upload', 'Upload files'],
  ['files:read', 'Download and list files'],
  ['reports:read', 'Read reports'],
  ['reports:manage_plans', 'Manage SalesPlan currencies and KPI FX snapshots'],
  ['audit:read', 'Read audit timeline'],
  ['admin:queues', 'Access Bull queue dashboard'],
  ['panel_catalog:read', 'Read panel catalog and calculator reference data'],
  ['panel_catalog:manage', 'Manage panel color catalog'],
  ['calculations:read', 'Read own calculations'],
  ['calculations:read_all', 'Read all calculations'],
  ['calculations:create', 'Create calculations'],
  ['calculations:update', 'Update draft calculations'],
  ['calculations:delete', 'Delete calculations'],
  ['quotes:read', 'Read own panel quotes'],
  ['quotes:read_all', 'Read all panel quotes'],
  ['quotes:create', 'Create panel quotes from calculations'],
  ['quotes:update', 'Update panel quote status'],
  ['quotes:approve', 'Approve panel quotes (privileged commercial approval)'],
  ['quotes:client_accept', 'Record customer acceptance of an approved quote'],
  ['supplier_orders:manage', 'Create and operate client Deal supplier orders'],
  [
    'supplier_orders:confirm_client_delivery',
    'Confirm actual goods delivery to the client',
  ],
  ['installation:schedule', 'Schedule deal installation dates'],
  ['installation:assess', 'Record lightweight installation assessment notes'],
  ['installation:confirm_work', 'Confirm installation work as installer'],
  [
    'installation:confirm_supervisor',
    'Confirm installation completion as HEAD or DIRECTOR',
  ],
  ['currency_rates:read', 'Read the active CNY to USD rate'],
  ['currency_rates:manage', 'Manage the centralized CNY to USD rate'],
  ['panel_pricing:manage', 'Manage supplier CNY panel thickness prices'],
] as const;

export type PermissionSlug = (typeof PERMISSION_DEFINITIONS)[number][0];

export const TARGET_ROLE_NAMES = [
  RoleName.ADMIN,
  RoleName.DIRECTOR,
  RoleName.HEAD,
  RoleName.MANAGER,
  RoleName.ACCOUNTANT,
  RoleName.STOREKEEPER,
  RoleName.INSTALLER,
] as const;

export type TargetRoleName = (typeof TARGET_ROLE_NAMES)[number];

const ADMIN_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'users:read',
  'users:create',
  'users:write',
  'users:manage',
  'admin:queues',
];

const DIRECTOR_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'users:read',
  'references:read',
  'products:read',
  'products:read_purchase_price',
  'clients:read',
  'clients:read_all',
  'leads:read',
  'leads:read_all',
  'tasks:read',
  'tasks:read_all',
  'deals:read',
  'deals:read_all',
  'orders:read',
  'files:read',
  'reports:read',
  'reports:manage_plans',
  'audit:read',
  'panel_catalog:read',
  'calculations:read',
  'calculations:read_all',
  'quotes:read',
  'quotes:read_all',
  'inventory:read',
  'warehouse_purchases:plan',
  'currency_rates:read',
  'currency_rates:manage',
  'supplier_orders:manage',
  'supplier_orders:confirm_client_delivery',
  'installation:schedule',
  'installation:confirm_supervisor',
  'installation:assess',
];

const HEAD_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'users:read',
  'references:read',
  'references:create',
  'references:update',
  'references:delete',
  'products:read',
  'products:create',
  'products:update',
  'products:delete',
  'products:manage_prices',
  'products:read_purchase_price',
  'clients:read',
  'clients:read_all',
  'clients:create',
  'clients:update',
  'clients:delete',
  'leads:read',
  'leads:read_all',
  'leads:create',
  'leads:update',
  'leads:delete',
  'leads:qualify',
  'leads:commercial_qualify',
  'leads:assign',
  'tasks:read',
  'tasks:read_all',
  'tasks:create',
  'tasks:update',
  'tasks:delete',
  'deals:read',
  'deals:read_all',
  'deals:create',
  'deals:update',
  'deals:delete',
  'deals:create_offer',
  'deals:approve_offer',
  'deals:stage_exception',
  'deals:override_terminal',
  'orders:read',
  'orders:create',
  'orders:cancel',
  'payments:create',
  'deliveries:create',
  'inventory:read',
  'inventory:manage',
  'warehouse_purchases:plan',
  'files:upload',
  'files:read',
  'reports:read',
  'audit:read',
  'panel_catalog:read',
  'panel_catalog:manage',
  'panel_pricing:manage',
  'calculations:read',
  'calculations:read_all',
  'calculations:create',
  'calculations:update',
  'calculations:delete',
  'quotes:read',
  'quotes:read_all',
  'quotes:create',
  'quotes:update',
  'quotes:approve',
  'currency_rates:read',
  'supplier_orders:manage',
  'supplier_orders:confirm_client_delivery',
  'installation:schedule',
  'installation:confirm_supervisor',
  'installation:assess',
];

const MANAGER_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'references:read',
  'products:read',
  'clients:read',
  'clients:create',
  'clients:update',
  'leads:read',
  'leads:create',
  'leads:update',
  'leads:qualify',
  'tasks:read',
  'tasks:create',
  'tasks:update',
  'deals:read',
  'deals:create',
  'deals:update',
  'deals:create_offer',
  'orders:read',
  'orders:create',
  'orders:cancel',
  'payments:create',
  'deliveries:create',
  'files:upload',
  'files:read',
  'audit:read',
  'panel_catalog:read',
  'panel_catalog:manage',
  'calculations:read',
  'calculations:create',
  'calculations:update',
  'calculations:delete',
  'quotes:read',
  'quotes:create',
  'quotes:update',
  'quotes:client_accept',
  'currency_rates:read',
  'supplier_orders:confirm_client_delivery',
];

const ACCOUNTANT_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'products:read',
  'clients:read',
  'clients:read_all',
  'deals:read',
  'deals:read_all',
  'orders:read',
  'payments:confirm',
  'files:read',
  'audit:read',
  'currency_rates:read',
];

const STOREKEEPER_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'references:read',
  'products:read',
  'orders:read',
  'deliveries:create',
  'inventory:read',
  'inventory:manage',
  'warehouse_purchases:receive',
];

const INSTALLER_PERMISSIONS: PermissionSlug[] = [
  'auth:me',
  'deals:read',
  'installation:assess',
  'installation:confirm_work',
];

export const ROLE_PERMISSION_SLUGS: Record<
  RoleName,
  readonly PermissionSlug[]
> = {
  [RoleName.ADMIN]: ADMIN_PERMISSIONS,
  [RoleName.DIRECTOR]: DIRECTOR_PERMISSIONS,
  [RoleName.HEAD]: HEAD_PERMISSIONS,
  [RoleName.MANAGER]: MANAGER_PERMISSIONS,
  [RoleName.ACCOUNTANT]: ACCOUNTANT_PERMISSIONS,
  [RoleName.STOREKEEPER]: STOREKEEPER_PERMISSIONS,
  [RoleName.INSTALLER]: INSTALLER_PERMISSIONS,
};

export const BUSINESS_MUTATION_PERMISSIONS = [
  'payments:confirm',
  'reports:manage_plans',
  'quotes:approve',
  'quotes:client_accept',
  'leads:commercial_qualify',
  'currency_rates:manage',
  'panel_pricing:manage',
  'supplier_orders:manage',
  'supplier_orders:confirm_client_delivery',
  'warehouse_purchases:plan',
  'warehouse_purchases:receive',
  'installation:schedule',
  'installation:assess',
  'installation:confirm_work',
  'installation:confirm_supervisor',
] as const;

export function roleHasPermission(roleName: RoleName, slug: string): boolean {
  return ROLE_PERMISSION_SLUGS[roleName].includes(slug as PermissionSlug);
}
