import type { FacadeNormDefinition } from './facade-norms';

export type FacadeSystemTable = {
  code: string;
  normSetCode: string;
  nameRu: string;
  nameEn: string;
  nameUz: string;
  hplThicknessMm: number;
  insulationThicknessMm: number | null;
  fastening: 'DRY' | 'ADHESIVE';
  panelWidthMm: number | null;
  panelHeightMm: number | null;
  panelAreaM2: string | null;
  norms: readonly FacadeNormDefinition[];
};

const shared = {
  paronite50x80: {
    code: 'paronite_pad_50x80',
    nameRu: 'Паронит под кронштейн 50×80 мм',
    nameEn: 'Paronite pad for bracket 50×80 mm',
    nameUz: 'Kronshteyn uchun paronit 50×80 mm',
    category: 'SUBSYSTEM' as const,
    unit: 'PCS' as const,
    qtyPerM2: '4.03',
    spec: { sizeMm: '50×80' },
  },
  paronite50x100: {
    code: 'paronite_pad_50x100',
    nameRu: 'Паронит под кронштейн 50×100 мм',
    nameEn: 'Paronite pad for bracket 50×100 mm',
    nameUz: 'Kronshteyn uchun paronit 50×100 mm',
    category: 'SUBSYSTEM' as const,
    unit: 'PCS' as const,
    qtyPerM2: '0.81',
    spec: { sizeMm: '50×100' },
  },
  profileT: {
    code: 'profile_t_80x50_t12_galvanized',
    nameRu: 'Профиль вертикальный T 80×50 мм, t=1,2 мм, оцинкованный',
    nameEn: 'Vertical T profile 80×50 mm, t=1.2 mm, galvanized',
    nameUz: 'Vertikal T profil 80×50 mm, t=1,2 mm, ruxlangan',
    category: 'SUBSYSTEM' as const,
    unit: 'LM' as const,
    qtyPerM2: '1.67',
    spec: { sectionMm: '80×50', thicknessMm: 1.2, coating: 'galvanized', shape: 'T' },
  },
  profileL5080: {
    code: 'profile_l_50x80_t15_facade_galvanized',
    nameRu: 'Профиль угловой L 50×80 мм, t=1,5 мм, на фасад, оцинкованный',
    nameEn: 'Corner L profile 50×80 mm, t=1.5 mm, facade, galvanized',
    nameUz: 'Fasad uchun burchak L profil 50×80 mm, t=1,5 mm, ruxlangan',
    category: 'SUBSYSTEM' as const,
    unit: 'LM' as const,
    qtyPerM2: '0.67',
    spec: { sectionMm: '50×80', thicknessMm: 1.5, coating: 'galvanized', shape: 'L', use: 'facade' },
  },
  profileL5040: {
    code: 'profile_l_50x40_t15_slopes_galvanized',
    nameRu: 'Профиль угловой L 50×40 мм, t=1,5 мм, на откосы, оцинкованный',
    nameEn: 'Corner L profile 50×40 mm, t=1.5 mm, slopes, galvanized',
    nameUz: 'Qiyaliklar uchun burchak L profil 50×40 mm, t=1,5 mm, ruxlangan',
    category: 'SUBSYSTEM' as const,
    unit: 'LM' as const,
    qtyPerM2: '0.07',
    spec: { sectionMm: '50×40', thicknessMm: 1.5, coating: 'galvanized', shape: 'L', use: 'slopes' },
  },
  anchor880: {
    code: 'anchor_bracket_8x80',
    nameRu: 'Анкер для кронштейна 8×80 мм',
    nameEn: 'Bracket anchor 8×80 mm',
    nameUz: 'Kronshteyn ankori 8×80 mm',
    category: 'FASTENER' as const,
    unit: 'PCS' as const,
    qtyPerM2: '4.03',
    spec: { sizeMm: '8×80' },
  },
  anchor10100: {
    code: 'anchor_bracket_10x100',
    nameRu: 'Анкер для кронштейна 10×100 мм',
    nameEn: 'Bracket anchor 10×100 mm',
    nameUz: 'Kronshteyn ankori 10×100 mm',
    category: 'FASTENER' as const,
    unit: 'PCS' as const,
    qtyPerM2: '1.61',
    spec: { sizeMm: '10×100' },
  },
  epdm: {
    code: 'epdm_tape_60_profile',
    nameRu: 'Лента EPDM 60 мм на профиль',
    nameEn: 'EPDM tape 60 mm on profile',
    nameUz: 'Profil uchun EPDM lenta 60 mm',
    category: 'SEALING_TAPE' as const,
    unit: 'LM' as const,
    qtyPerM2: '1.34',
    spec: { widthMm: 60, material: 'EPDM' },
  },
  membraneTape: {
    code: 'membrane_joint_tape',
    nameRu: 'Лента для мембраны',
    nameEn: 'Membrane tape',
    nameUz: 'Membrana lentasi',
    category: 'SEALING_TAPE' as const,
    unit: 'LM' as const,
    qtyPerM2: '1.21',
    spec: {},
  },
  rivet510: {
    code: 'rivet_5x10_head_8_10_cutoff_galvanized',
    nameRu: 'Заклёпки 5×10 мм, шляпка 8–10, с отсечкой, оцинкованные',
    nameEn: 'Rivets 5×10 mm, head 8–10, with cut-off, galvanized',
    nameUz: 'Zaklyopkalar 5×10 mm, shapka 8–10, kesish bilan, ruxlangan',
    category: 'FASTENER' as const,
    unit: 'PCS' as const,
    qtyPerM2: '12.09',
    spec: { sizeMm: '5×10', headMm: '8–10', cutoff: 'yes', coating: 'galvanized' },
  },
  rivetHpl: {
    code: 'rivet_hpl_5x15_head_15_slope',
    nameRu: 'Заклёпки для HPL 5×15 мм, шляпка 15 мм, включая откос',
    nameEn: 'HPL rivets 5×15 mm, head 15 mm, including slope',
    nameUz: 'HPL zaklyopkalari 5×15 mm, shapka 15 mm, qiyalik bilan',
    category: 'FASTENER' as const,
    unit: 'PCS' as const,
    qtyPerM2: '10.75',
    spec: { sizeMm: '5×15', headMm: 15, includesSlope: 'yes' },
  },
};

function line(
  sortOrder: number,
  row: Omit<FacadeNormDefinition, 'sortOrder'>,
): FacadeNormDefinition {
  return { sortOrder, ...row };
}

export const HPL_DRY_6MM_50MM: FacadeSystemTable = {
  code: 'HPL_DRY_6MM_50MM',
  normSetCode: 'HPL_DRY_6MM_50MM_V1',
  nameRu: 'Сухой монтаж — HPL 6 мм, базальтовая плита 50 мм',
  nameEn: 'Dry fixing — HPL 6 mm, basalt board 50 mm',
  nameUz: 'Quruq montaj — HPL 6 mm, bazalt plita 50 mm',
  hplThicknessMm: 6,
  insulationThicknessMm: 50,
  fastening: 'DRY',
  panelWidthMm: 1220,
  panelHeightMm: 3050,
  panelAreaM2: '3.721',
  norms: [
    line(1, {
      code: 'hpl_panel_1220_3050_6mm',
      nameRu: 'HPL панель 1220×3050 мм, 6 мм',
      nameEn: 'HPL panel 1220×3050 mm, 6 mm',
      nameUz: 'HPL panel 1220×3050 mm, 6 mm',
      category: 'HPL',
      unit: 'M2',
      qtyPerM2: '1.06',
      spec: { sizeMm: '1220×3050', thicknessMm: 6, areaM2: '3.721' },
    }),
    line(2, {
      code: 'basalt_board_1_layer_50mm',
      nameRu: 'Базальтовая плита в 1 слой, 50 мм',
      nameEn: 'Basalt board, 1 layer, 50 mm',
      nameUz: 'Bazalt plita, 1 qatlam, 50 mm',
      category: 'INSULATION',
      unit: 'M2',
      qtyPerM2: '1.05',
      spec: { layers: 1, thicknessMm: 50 },
    }),
    line(3, {
      code: 'facade_membrane',
      nameRu: 'Мембрана',
      nameEn: 'Membrane',
      nameUz: 'Membrana',
      category: 'MEMBRANE',
      unit: 'M2',
      qtyPerM2: '1.16',
      spec: {},
    }),
    line(4, {
      code: 'bracket_50x100x80_t2_painted_ss',
      nameRu: 'Кронштейн 50×100×80, t=2,0 мм, нерж. крашеный',
      nameEn: 'Bracket 50×100×80, t=2.0 mm, painted stainless',
      nameUz: 'Kronshteyn 50×100×80, t=2,0 mm, bo‘yalgan zanglamas',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '4.03',
      spec: { sectionMm: '50×100×80', thicknessMm: 2.0, material: 'painted stainless' },
    }),
    line(5, {
      code: 'bracket_50x100x100_t2_painted_ss',
      nameRu: 'Кронштейн 50×100×100, t=2,0 мм, нерж. крашеный',
      nameEn: 'Bracket 50×100×100, t=2.0 mm, painted stainless',
      nameUz: 'Kronshteyn 50×100×100, t=2,0 mm, bo‘yalgan zanglamas',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '0.81',
      spec: { sectionMm: '50×100×100', thicknessMm: 2.0, material: 'painted stainless' },
    }),
    line(6, shared.paronite50x80),
    line(7, shared.paronite50x100),
    line(8, shared.profileT),
    line(9, shared.profileL5080),
    line(10, shared.profileL5040),
    line(11, {
      code: 'fire_cutoff_l_100x50_t12',
      nameRu: 'Противопожарная отсечка L 100×50 мм, t=1,2 мм',
      nameEn: 'Fire cut-off L 100×50 mm, t=1.2 mm',
      nameUz: 'Yong‘inga qarshi kesish L 100×50 mm, t=1,2 mm',
      category: 'SUBSYSTEM',
      unit: 'LM',
      qtyPerM2: '0.09',
      spec: { sectionMm: '100×50', thicknessMm: 1.2, shape: 'L' },
    }),
    line(12, shared.anchor880),
    line(13, shared.anchor10100),
    line(14, {
      code: 'dowel_nail_mushroom_8x115',
      nameRu: 'Дюбель-гвоздь грибок 8×115',
      nameEn: 'Mushroom dowel nail 8×115',
      nameUz: 'Qo‘ziqorin dyubel-mix 8×115',
      category: 'FASTENER',
      unit: 'PCS',
      qtyPerM2: '6.99',
      spec: { sizeMm: '8×115' },
    }),
    line(15, shared.epdm),
    line(16, shared.membraneTape),
    line(17, shared.rivet510),
    line(18, shared.rivetHpl),
  ],
};

export const HPL_DRY_8MM_80MM: FacadeSystemTable = {
  code: 'HPL_DRY_8MM_80MM',
  normSetCode: 'HPL_DRY_8MM_80MM_V1',
  nameRu: 'Сухой монтаж — HPL 8 мм, базальтовая плита 80 мм',
  nameEn: 'Dry fixing — HPL 8 mm, basalt board 80 mm',
  nameUz: 'Quruq montaj — HPL 8 mm, bazalt plita 80 mm',
  hplThicknessMm: 8,
  insulationThicknessMm: 80,
  fastening: 'DRY',
  panelWidthMm: 1220,
  panelHeightMm: 3050,
  panelAreaM2: '3.721',
  norms: [
    line(1, {
      code: 'hpl_panel_1220_3050_8mm',
      nameRu: 'HPL панель 1220×3050 мм, 8 мм',
      nameEn: 'HPL panel 1220×3050 mm, 8 mm',
      nameUz: 'HPL panel 1220×3050 mm, 8 mm',
      category: 'HPL',
      unit: 'M2',
      qtyPerM2: '1.06',
      spec: { sizeMm: '1220×3050', thicknessMm: 8, areaM2: '3.721' },
    }),
    line(2, {
      code: 'basalt_board_1_layer_80mm',
      nameRu: 'Базальтовая плита в 1 слой, 80 мм',
      nameEn: 'Basalt board, 1 layer, 80 mm',
      nameUz: 'Bazalt plita, 1 qatlam, 80 mm',
      category: 'INSULATION',
      unit: 'M2',
      qtyPerM2: '1.05',
      spec: { layers: 1, thicknessMm: 80 },
    }),
    line(3, {
      code: 'facade_membrane_ng',
      nameRu: 'Мембрана НГ',
      nameEn: 'Non-combustible membrane',
      nameUz: 'Yonmaydigan membrana',
      category: 'MEMBRANE',
      unit: 'M2',
      qtyPerM2: '1.16',
      spec: { fireClass: 'NG' },
    }),
    line(4, {
      code: 'bracket_50x130x80_t2_painted_ss',
      nameRu: 'Кронштейн 50×130×80, t=2,0 мм, нерж. крашеный',
      nameEn: 'Bracket 50×130×80, t=2.0 mm, painted stainless',
      nameUz: 'Kronshteyn 50×130×80, t=2,0 mm, bo‘yalgan zanglamas',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '4.03',
      spec: { sectionMm: '50×130×80', thicknessMm: 2.0, material: 'painted stainless' },
    }),
    line(5, {
      code: 'bracket_50x130x100_t2_painted_ss',
      nameRu: 'Кронштейн 50×130×100, t=2,0 мм, нерж. крашеный',
      nameEn: 'Bracket 50×130×100, t=2.0 mm, painted stainless',
      nameUz: 'Kronshteyn 50×130×100, t=2,0 mm, bo‘yalgan zanglamas',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '0.81',
      spec: { sectionMm: '50×130×100', thicknessMm: 2.0, material: 'painted stainless' },
    }),
    line(6, shared.paronite50x80),
    line(7, shared.paronite50x100),
    line(8, shared.profileT),
    line(9, shared.profileL5080),
    line(10, shared.profileL5040),
    line(11, {
      code: 'fire_cutoff_l_100x50_t12_galvanized',
      nameRu: 'Противопожарная отсечка L 100×50 мм, t=1,2 мм, оцинкованная',
      nameEn: 'Fire cut-off L 100×50 mm, t=1.2 mm, galvanized',
      nameUz: 'Yong‘inga qarshi kesish L 100×50 mm, t=1,2 mm, ruxlangan',
      category: 'SUBSYSTEM',
      unit: 'LM',
      qtyPerM2: '0.09',
      spec: { sectionMm: '100×50', thicknessMm: 1.2, shape: 'L', coating: 'galvanized' },
    }),
    line(12, shared.anchor880),
    line(13, shared.anchor10100),
    line(14, {
      code: 'dowel_nail_mushroom_8x135',
      nameRu: 'Дюбель-гвоздь грибок 8×135',
      nameEn: 'Mushroom dowel nail 8×135',
      nameUz: 'Qo‘ziqorin dyubel-mix 8×135',
      category: 'FASTENER',
      unit: 'PCS',
      qtyPerM2: '7.26',
      spec: { sizeMm: '8×135' },
    }),
    line(15, shared.epdm),
    line(16, shared.membraneTape),
    line(17, shared.rivet510),
    line(18, shared.rivetHpl),
  ],
};

export const HPL_ADHESIVE_4MM: FacadeSystemTable = {
  code: 'HPL_ADHESIVE_4MM',
  normSetCode: 'HPL_ADHESIVE_4MM_V1',
  nameRu: 'Клеевой монтаж — HPL 4 мм',
  nameEn: 'Adhesive fixing — HPL 4 mm',
  nameUz: 'Yelimli montaj — HPL 4 mm',
  hplThicknessMm: 4,
  insulationThicknessMm: null,
  fastening: 'ADHESIVE',
  panelWidthMm: null,
  panelHeightMm: null,
  panelAreaM2: null,
  norms: [
    line(1, {
      code: 'profile_l_60x40x12_galvanized',
      nameRu: 'L-профиль оцинкованный 60×40×1,2',
      nameEn: 'Galvanized L-profile 60×40×1.2',
      nameUz: 'Ruxlangan L-profil 60×40×1,2',
      category: 'SUBSYSTEM',
      unit: 'LM',
      qtyPerM2: '2.78',
      spec: { sectionMm: '60×40×1.2', coating: 'galvanized', shape: 'L' },
    }),
    line(2, {
      code: 'profile_t_80x50x12_galvanized',
      nameRu: 'T-профиль оцинкованный 80×50×1,2',
      nameEn: 'Galvanized T-profile 80×50×1.2',
      nameUz: 'Ruxlangan T-profil 80×50×1,2',
      category: 'SUBSYSTEM',
      unit: 'LM',
      qtyPerM2: '0.51',
      spec: { sectionMm: '80×50×1.2', coating: 'galvanized', shape: 'T' },
    }),
    line(3, {
      code: 'sikatack_fixing_tape',
      nameRu: 'Двусторонний скотч SikaTack fixing tape',
      nameEn: 'Double-sided tape SikaTack fixing tape',
      nameUz: 'Ikki tomonlama skotch SikaTack fixing tape',
      category: 'SEALING_TAPE',
      unit: 'LM',
      qtyPerM2: '4.00',
      spec: { product: 'SikaTack fixing tape' },
    }),
    line(4, {
      code: 'sikatack_panel_sausage',
      nameRu: 'Колбасный клей SikaTack Panel',
      nameEn: 'Sausage adhesive SikaTack Panel',
      nameUz: 'Kolbasa yelimi SikaTack Panel',
      category: 'ADDITIONAL',
      unit: 'PCS',
      qtyPerM2: '0.36',
      spec: { product: 'SikaTack Panel' },
    }),
    line(5, {
      code: 'sikateck_panel_primer',
      nameRu: 'Праймер SikaTeck Panel',
      nameEn: 'Primer SikaTeck Panel',
      nameUz: 'Primer SikaTeck Panel',
      category: 'ADDITIONAL',
      unit: 'LITER',
      qtyPerM2: '0.06',
      spec: { product: 'SikaTeck Panel' },
    }),
    line(6, {
      code: 'sikateck_panel_activator',
      nameRu: 'Активатор SikaTeck Panel',
      nameEn: 'Activator SikaTeck Panel',
      nameUz: 'Aktivator SikaTeck Panel',
      category: 'ADDITIONAL',
      unit: 'LITER',
      qtyPerM2: '0.06',
      spec: { product: 'SikaTeck Panel' },
    }),
    line(7, {
      code: 'bracket_sliding_80x100_2mm',
      nameRu: 'Кронштейн скользящий 80×100, 2 мм',
      nameEn: 'Sliding bracket 80×100, 2 mm',
      nameUz: 'Sirpanuvchi kronshteyn 80×100, 2 mm',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '4.69',
      spec: { sectionMm: '80×100', thicknessMm: 2, type: 'sliding' },
    }),
    line(8, {
      code: 'bracket_fixed_80x100_2mm',
      nameRu: 'Кронштейн фиксированный 80×100, 2 мм',
      nameEn: 'Fixed bracket 80×100, 2 mm',
      nameUz: 'Qotiruvchi kronshteyn 80×100, 2 mm',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '0.78',
      spec: { sectionMm: '80×100', thicknessMm: 2, type: 'fixed' },
    }),
    line(9, {
      code: 'anchor_dowel_rmg_ad_dacromet_10x100',
      nameRu: 'Фасадный анкерный дюбель RMG (полиамид) AD DACROMET 10×100',
      nameEn: 'Facade anchor dowel RMG (polyamide) AD DACROMET 10×100',
      nameUz: 'Fasad anker dyubeli RMG (poliamid) AD DACROMET 10×100',
      category: 'FASTENER',
      unit: 'PCS',
      qtyPerM2: '6.25',
      spec: { product: 'RMG AD DACROMET', sizeMm: '10×100', material: 'polyamide' },
    }),
    line(10, {
      code: 'paronite_pad_bracket_80x100',
      nameRu: 'Термопрокладка паронитовая под кронштейн 80×100',
      nameEn: 'Paronite thermal pad for bracket 80×100',
      nameUz: 'Kronshteyn 80×100 uchun paronit termoqistirma',
      category: 'SUBSYSTEM',
      unit: 'PCS',
      qtyPerM2: '5.47',
      spec: { sizeMm: '80×100', material: 'paronite' },
    }),
  ],
};

export const FACADE_SYSTEM_TABLES: readonly FacadeSystemTable[] = [
  HPL_DRY_6MM_50MM,
  HPL_DRY_8MM_80MM,
  HPL_ADHESIVE_4MM,
];

export const FACADE_SYSTEM_META: Record<
  string,
  Pick<
    FacadeSystemTable,
    'hplThicknessMm' | 'insulationThicknessMm' | 'fastening'
  >
> = Object.fromEntries(
  FACADE_SYSTEM_TABLES.map((table) => [
    table.code,
    {
      hplThicknessMm: table.hplThicknessMm,
      insulationThicknessMm: table.insulationThicknessMm,
      fastening: table.fastening,
    },
  ]),
);
